import React, { useState, useEffect } from 'react';
import { Loader, Card, FormField } from '../components';

const RenderCards = ({ data, title, onImageClick }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} onImageClick={onImageClick} />);
  }
  return <h2 className="mt-5 font-medium text-zinc-500 text-lg">{title}</h2>;
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState('');
  const [searchedResults, setSearchedResults] = useState(null);
  const [searchTimeout, setSearchTimeout] = useState(null);
  
  const [selectedImage, setSelectedImage] = useState(null);

  const fetchPosts = async () => {
    setLoading(true);
    try {
      const response = await fetch('http://localhost:8080/api/v1/post', {
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
      });
      if (response.ok) {
        const result = await response.json();
        setAllPosts(result.data.reverse());
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchPosts(); }, []);

  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);
    setSearchTimeout(
      setTimeout(() => {
        const searchResult = allPosts.filter((item) => 
          item.name.toLowerCase().includes(searchText.toLowerCase()) || 
          item.prompt.toLowerCase().includes(searchText.toLowerCase())
        );
        setSearchedResults(searchResult);
      }, 500)
    );
  };

  return (
    <section className="w-full relative">
      <div className="mb-12 text-center max-w-3xl mx-auto">
        <h1 className="font-extrabold text-white text-4xl tracking-tight mb-4">
          Community Showcase
        </h1>
        <p className="text-zinc-400 text-base">
          Explore a curated gallery of high-definition visuals generated by our users using state-of-the-art diffusion models.
        </p>
      </div>

      <div className="mb-10 max-w-2xl mx-auto">
        <FormField
          type="text"
          name="text"
          placeholder="🔍 Search for prompts, artists, or keywords..."
          value={searchText}
          handleChange={handleSearchChange}
        />
      </div>

      <div>
        {loading ? (
          <div className="flex justify-center items-center py-20"><Loader /></div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-zinc-400 text-lg mb-6">
                Search results for <span className="text-white">"{searchText}"</span>
              </h2>
            )}
            <div className="columns-1 sm:columns-2 md:columns-3 lg:columns-4 gap-4 space-y-4">
              {searchText ? (
                <RenderCards data={searchedResults} title="No search results found" onImageClick={setSelectedImage} />
              ) : (
                <RenderCards data={allPosts} title="No gallery posts found yet." onImageClick={setSelectedImage} />
              )}
            </div>
          </>
        )}
      </div>

      {selectedImage && (
        <div 
          className="fixed inset-0 z-[100] flex justify-center items-center bg-black/95 backdrop-blur-sm p-4 sm:p-10 animate-fade-in"
          onClick={() => setSelectedImage(null)}
        >
          <button 
            className="absolute top-6 right-8 text-zinc-500 hover:text-white text-4xl font-light transition-colors"
            onClick={() => setSelectedImage(null)}
          >
            ×
          </button>
          
          <div 
            className="relative max-w-6xl w-full flex flex-col items-center gap-6 cursor-default"
            onClick={(e) => e.stopPropagation()}
          >
            <img 
              src={selectedImage.photo} 
              alt={selectedImage.prompt} 
              className="w-full max-h-[75vh] object-contain rounded-lg border border-zinc-800"
            />
            
            <div className="bg-zinc-900 border border-zinc-800 p-5 rounded-lg w-full max-w-4xl shadow-xl flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
              <div>
                <p className="text-zinc-200 text-base leading-relaxed font-medium">{selectedImage.prompt}</p>
                <p className="text-indigo-400 font-medium mt-1 text-sm">Generated by {selectedImage.name}</p>
              </div>
              <a 
                href={selectedImage.photo} 
                download={`VisionAI_${selectedImage.name}.png`}
                className="shrink-0 bg-indigo-600 hover:bg-indigo-500 text-white px-5 py-2.5 rounded-lg transition-colors flex items-center gap-2 text-sm font-medium"
              >
                <span className="font-bold">↓</span> Download HD
              </a>
            </div>
          </div>
        </div>
      )}
    </section>
  );
};

export default Home;