import React, { useState, useEffect } from 'react';
import { Loader, Card, FormField } from '../components';
import { useAuth } from '../context/AuthContext';

const RenderCards = ({ data, title, onImageClick, onDelete, loggedInUserId }) => {
  if (data?.length > 0) {
    return data.map((post) => (
      <Card 
        key={post._id} 
        {...post} 
        onImageClick={onImageClick} 
        onDelete={onDelete}
        isMine={loggedInUserId && post.creator === loggedInUserId} 
      />
    ));
  }
  return <h2 className="mt-5 font-medium text-slate-500 text-lg">{title}</h2>;
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState([]);
  const [searchText, setSearchText] = useState('');
  const [searchedResults, setSearchedResults] = useState(null);
  const [selectedImage, setSelectedImage] = useState(null);
  
  const { user } = useAuth(); 

  const fetchPosts = async () => {
    setLoading(true);
    try {
      // FIXED: Corrected closing backtick
      const response = await fetch(`${import.meta.env.VITE_BACKEND_URL}/api/v1/post`);
      if (response.ok) {
        const result = await response.json();
        setAllPosts(result.data.reverse());
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { 
    fetchPosts(); 
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleSearchChange = (e) => {
    setSearchText(e.target.value);
    setTimeout(() => {
      const results = allPosts.filter((item) => 
        item.name.toLowerCase().includes(e.target.value.toLowerCase()) || 
        item.prompt.toLowerCase().includes(e.target.value.toLowerCase())
      );
      setSearchedResults(results);
    }, 500);
  };

  const handleDeletePost = async (id) => {
    if (window.confirm("Are you sure you want to delete your artwork?")) {
      try {
        // FIXED: Cleaned up the broken URL template literal
        await fetch(`${import.meta.env.VITE_BACKEND_URL}/api/v1/post/${id}`, { 
          method: 'DELETE',
          credentials: 'include' 
        });
        setAllPosts(allPosts.filter(post => post._id !== id));
      } catch (error) {
        console.error('Failed to delete', error);
      }
    }
  };

  return (
    <section className="w-full relative">
      <div className="mb-12 text-center max-w-3xl mx-auto">
        <h1 className="font-black text-slate-900 text-4xl tracking-tight mb-4">Community Showcase</h1>
        <p className="text-slate-500 text-base">Explore high-definition visuals generated by the community.</p>
      </div>

      <div className="mb-12 max-w-3xl mx-auto">
        <FormField type="text" name="text" placeholder="🔍 Search prompts or artists..." value={searchText} handleChange={handleSearchChange} />
      </div>

      <div>
        {loading ? (
          <div className="flex justify-center py-20"><Loader /></div>
        ) : (
          <div className="columns-1 sm:columns-2 md:columns-2 lg:columns-3 xl:columns-3 gap-6 space-y-6">
            {searchText ? (
              <RenderCards data={searchedResults} title="No search results found" onImageClick={setSelectedImage} onDelete={handleDeletePost} loggedInUserId={user?._id} />
            ) : (
              <RenderCards data={allPosts} title="No gallery posts found yet." onImageClick={setSelectedImage} onDelete={handleDeletePost} loggedInUserId={user?._id} />
            )}
          </div>
        )}
      </div>

      {selectedImage && (
        <div className="fixed inset-0 z-[100] flex justify-center items-center bg-slate-900/60 backdrop-blur-sm p-4" onClick={() => setSelectedImage(null)}>
          <div className="relative max-w-5xl w-full flex flex-col items-center gap-4" onClick={(e) => e.stopPropagation()}>
            <img src={selectedImage.photo} alt={selectedImage.prompt} className="w-full max-h-[75vh] object-contain rounded-xl shadow-2xl" />
            <div className="bg-white p-5 rounded-xl w-full max-w-4xl shadow-xl flex justify-between items-center gap-4">
              <div>
                <p className="text-slate-800 font-medium">{selectedImage.prompt}</p>
                <p className="text-indigo-600 font-medium mt-1 text-sm">By {selectedImage.name}</p>
              </div>
            </div>
          </div>
        </div>
      )}
    </section>
  );
};

export default Home;